### ISSUE TITLE
[nuxt] [request error] [unhandled] [500] supabaseUrl is required.

### ISSUE THREAD

**Issue by shinshin86** [Chew/ChessTools#1]
Hello! It's interesting project.

I would like to try it, but I got the following error

```
[nuxt] [request error] [unhandled] [500] supabaseUrl is required.
```

It seems to me that I need to have a `.env` file with the following credentials for supabase, am I right?

```
SUPABASE_URL="https://example.supabase.co"
SUPABASE_KEY="<your_key>"
```

https://supabase.nuxtjs.org/get-started#installation

**Comment by shinshin86** [comment]
@Chew Thanks for the reply!

The `.env` file was not present in the execution directory because I ran it with it cloned from GitHub.
(Maybe my explanation was not clear. Sorry about that.)

When I ran it with the `.env` file in the project root, the error went away and the app started.
Thank you very much!

I thought adding these steps to the README would make it easier for other developers to build their environments, so I created a PR.

It would be my pleasure if you could check it out.

By the way, the `.env` file only needed the following description and it seemed to start without any problem at first, but if I am wrong, please point it out to me.

```
SUPABASE_URL="https://example.supabase.co"
SUPABASE_KEY="<your_key>"
```

**Comment by Chew** [comment]
You'll need the service key for some stuff like integrating linking and creating games. We could definitely add an .env.example and put the required values there just for people to know about it. Good advice!
