### ISSUE TITLE
Unlinked user profile should not be blank

### ISSUE THREAD

**Issue by jalpp** [Chew/ChessTools#24]
When the user has not verified any of the sites the profile just shows a white empty page with "your profile" sort of blank, should have call to action like link your accounts or maybe ? Rating stats or some sort of fake stats

**Comment by Chew** [comment]
All profiles are blank right now, this will be resolved in #3 so I'll close in favor of that.

**Comment by Chew** [comment]
Partially fixed with https://github.com/Chew/ChessTools/commit/12cd7c28f6e586ee0033dfe0425700a74c72e3d0 since your profile page is just an actual profile page now.
